### ISSUE TITLE
Creating a Contributor's Guide

### ISSUE THREAD

**Issue by anonimal** [glynos/cpp-netlib#24]
Hi everyone,

When fixing bugs in branch ```master```, I found out too late that they were resolved in ```0.12-release``` and ```0.13-release```. When wanting to PR other contributions, I could not find clear documentation that indicated which branch to PR too.

I'm wondering if a basic contributor's guide would be helpful to the project. Something that indicates workflow and/or any desired protocol. If the guide also included any style considerations, that would be helpful ([our guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md) is under development but has been helpful so far).

*Referencing [our interest](https://github.com/monero-project/kovri/issues/155) in cpp-netlib.*

**Comment by glynos** [comment]
There is this:

http://cpp-netlib.org/process.html

But it seems that this not prominent enough. A file such as CONTRIBUTING.md in the source root is a good idea.

**Comment by glynos** [comment]
https://github.com/glynos/cpp-netlib/blob/master/CONTRIBUTING.rst

**Comment by anonimal** [comment]
Excellent, thank you @glynos!

*Closing as resolved in 56c1711030a250a8345c9a2c54d7b267ce282567*

**Comment by glynos** [comment]
Bear in mind that the repo you should use for PRs in the future is https://github.com/cpp-netlib/cpp-netlib/.

Thanks for using our library!

**Comment by anonimal** [comment]
Ahhh, I can't believe I missed that :blush: A million thanks for clarifying this! :smile: :+1:
