### ISSUE TITLE
Fetched in submodule path 'libs/network/doc/_ext/breathe'

### ISSUE THREAD

**Issue by CARASO** [glynos/cpp-netlib#27]
When I type cmd "git submodule update",then I got the log below:

> 

Cloning into '.../cpp-netlib/deps/asio'...
Cloning into '.../cpp-netlib/deps/cxxopts'...
Cloning into '.../cpp-netlib/deps/googlemock'...
Cloning into '.../cpp-netlib/deps/googletest'...
Cloning into '.../cpp-netlib/deps/uri'...
Cloning into '.../cpp-netlib/libs/network/doc/_ext/breathe'...
Submodule path 'deps/asio': checked out '66e76b9e4252ff4681227d0d8e34374ec1fa20e5'
Submodule path 'deps/cxxopts': checked out 'aec97a6f53c3486fc51e0d9857f10b683180d668'
Submodule path 'deps/googlemock': checked out 'f7d03d2734759ee12b57d2dbcb695607d89e8e05'
Submodule path 'deps/googletest': checked out 'd225acc90bc3a8c420a9bcd1f033033c1ccd7fe0'
Submodule path 'deps/uri': checked out 'c16a46ecb6bf0c936179e324891a74b5e6d8f4d3'
error: Server does not allow request for unadvertised object 853385ef4f0c3dd126887750e20d5f7456065998
Fetched in submodule path 'libs/network/doc/_ext/breathe', but it did not contain 853385ef4f0c3dd126887750e20d5f7456065998. Direct fetching of that commit failed.

>

**Comment by glynos** [comment]
This repo is not up-to-date. Please use:

https://github.com/cpp-netlib/cpp-netlib.git

Your issue should have been fixed on that repo.

**Comment by CARASO** [comment]
@glynos Thanks a lot !
